### ISSUE TITLE
API Versioning strategy

### ISSUE THREAD

**Issue by mrsmitty** [paullisto-insight/mulesoft-spec-upload#12]
Thanks for adding this repo @paullisto-insight!

A thought on reviewing the code ( I haven't tested this). https://github.com/paullisto-insight/mulesoft-spec-upload/blob/main/.github/workflows/main.yml#L23 it uses the PR name to indicate version in `<group_id>/<asset_id>/<version>`.

Usually API version numbers seldom change as it's disruptive to consumers. We try limit versions to major functionality changes or significant changes to the schema. `${{ github.run_id }}` will give a value that links back to the GitHub Action run within the repository. 

This will allow linking the uploaded assets back to the workflow execution. Useful if the current PR has had multiple deployments.

**Comment by paullisto-insight** [comment]
@mrsmitty thank you for the code review and comment!

Mulesoft requires that the version fit the major, minor, patch Semantic Versioning model. Source: https://docs.mulesoft.com/exchange/to-change-raml-version. The main objective of the automation is to increment the patch number, and very occasionally the minor version, as the major version is hard-coded in **main.yml** with the argument `--apiVersion v1`. The API will fail to upload if the major version number in the PR name doesn't align to that argument (confirmed in the Action output resulting from PR ref #13 )

I had a similar thought to yours after sharing this repository because while the Pull Request name as the version enables greater control, it requires the user to manually enter the major, minor and patch version potentially resulting in accidental error.

The command in **main.yml** includes the `--apiVersion v1` argument which is the version that is used in the API URL, (i.e. www.example.com/**v1**/api/....) however perhaps the version in `<group_id>/<asset_id>/<version>` could be hardcoded to `/1.0.${{ github.run_id }}` to simply ensure that the patch number is unique, rather than entering major.minor.version. This will likely reduce the risk of accidental error. The concerns are that the patch numbers will not be sequential and that minor versions will require a hard code change to **main.yml**.

I will comment **mail.yml** with both options and edit the **README.md** to explain their uses as per this issue reference.

**Comment by paulwlisto** [comment]
Revised to use Releases instead. **main.yml** has been archived as **main.yml.old** in case someone wishes to refer to the PR method.
